# Generated by Django 3.2.13 on 2022-04-21 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Image')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Is Favorite')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('job_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Job Title')),
                ('current_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='Current Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('country_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country Code')),
                ('label', models.CharField(blank=True, max_length=50, null=True, verbose_name='Label')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='contacts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='ContactLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='contacts.contact')),
            ],
        ),
    ]
